### ISSUE TITLE
Question: Definition for TODO - Performance Comparison

### ISSUE THREAD

**Issue by raphaeleidus** [Kudo/react-native-v8#1]
It would be great to have some thoughts on what a performance comparison should look like. 
Is it timing around running a bunch of JS code?
Is it timing around making a bunch of bridge module calls?
Is it taking an app and comparing the scroll performance?
Some mix of all of the above?

If you can start with defining that TODO a little more clearly I might be able to start the comparison and send in a PR.

**Comment by Kudo** [comment]
@raphaeleidus Thank you for the good question.

I used to measure by the scripts from jsc-android-buildscripts.
https://github.com/react-native-community/jsc-android-buildscripts/tree/master/measure
There are some pure JS benchmarks and two React Native rendering cases.

However, we are not sure if that benchmarks fit with real apps.
If you have some idea, maybe it is worth to create a proposal at https://github.com/react-native-community/discussions-and-proposals.
Probably "Official benchmark for React Native app".

**Comment by Kudo** [comment]
Just to update that I had some result already.
https://github.com/Kudo/react-native-js-benchmark
I am going to close this issue and feel free to open new issue at that repo if you have any further questions.
Thank you so much.

**Comment by sapjax** [comment]
@Kudo 
According to the result, `v8 7.5.1 arm32 JIT` has the best performance?

**Comment by Kudo** [comment]
@sapjax Yes, and it should be expected.
jsc-android we only turn on Baseline JIT (and disabled DFG JIT and FTL JIT).
Hermes, on the other hand, does not have JIT. 

Well, memory usage / CPU / binary size might be another story compared with performance.
I will add memory / CPU benchmark if I have some free time.
