### ISSUE TITLE
Crash in V8PointerValue::Get

### ISSUE THREAD

**Issue by smacgregor** [Kudo/react-native-v8#10]
We started rolling out the 0.59.10 version of react-native-v8 (thank you for making that available!)

```
yarn add 'react-native-v8@>=0.59.10-patch.0 <0.59.11'
```

We are seeing this frequent crasher:

```
SIGSEGV
/data/app/com.foo-V_gIO-z59Y8CQLn3cc-OTg==/lib/arm64/libjscexecutor.so:182484
Segmentation violation (invalid memory reference)
Aug 8th, 2019, 22:27:18 PST

STACKTRACE

SIGSEGV Segmentation violation (invalid memory reference) 
    /data/app/com.foo-V_gIO-z59Y8CQLn3cc-OTg==/lib/arm64/libjscexecutor.so:182484 facebook::V8PointerValue::Get(v8::Isolate*) const
    /data/app/com.foo-V_gIO-z59Y8CQLn3cc-OTg==/lib/arm64/libjscexecutor.so:179952 facebook::JSIV8ValueConverter::ToV8String(facebook::V8Runtime const&, facebook::jsi::String const&)
    /data/app/com.foo-V_gIO-z59Y8CQLn3cc-OTg==/lib/arm64/libjscexecutor.so:162092 facebook::V8Runtime::getProperty(facebook::jsi::Object const&, facebook::jsi::String const&)
    /data/app/com.foo-V_gIO-z59Y8CQLn3cc-OTg==/lib/arm64/libjscexecutor.so:214480 facebook::jsi::dynamicFromValue(facebook::jsi::Runtime&, facebook::jsi::Value const&)
    /data/app/com.foo-V_gIO-z59Y8CQLn3cc-OTg==/lib/arm64/libjscexecutor.so:214164 facebook::jsi::dynamicFromValue(facebook::jsi::Runtime&, facebook::jsi::Value const&)
    /data/app/com.foo-V_gIO-z59Y8CQLn3cc-OTg==/lib/arm64/libjscexecutor.so:214164 facebook::jsi::dynamicFromValue(facebook::jsi::Runtime&, facebook::jsi::Value const&)
    /data/app/com.foo-V_gIO-z59Y8CQLn3cc-OTg==/lib/arm64/libjscexecutor.so:214164 facebook::jsi::dynamicFromValue(facebook::jsi::Runtime&, facebook::jsi::Value const&)
    /data/app/com.foo-V_gIO-z59Y8CQLn3cc-OTg==/lib/arm64/libjscexecutor.so:128500 facebook::react::JSIExecutor::callNativeModules(facebook::jsi::Value const&, bool)
    /data/app/com.foo-V_gIO-z59Y8CQLn3cc-OTg==/lib/arm64/libjscexecutor.so:134456 0x7942a73d38
    /data/app/com.foo-V_gIO-z59Y8CQLn3cc-OTg==/lib/arm64/libjscexecutor.so:177072 facebook::HostFunctionProxy::FunctionCallback(v8::FunctionCallbackInfo<v8::Value> const&)
    /data/app/com.foo-V_gIO-z59Y8CQLn3cc-OTg==/lib/arm64/libv8.so:11334156 0x793a06a20c
    /data/app/com.foo-V_gIO-z59Y8CQLn3cc-OTg==/lib/arm64/libv8.so:11333368 0x793a069ef8
    /data/app/com.foo-V_gIO-z59Y8CQLn3cc-OTg==/lib/arm64/libv8.so:19105740 0x793a7d37cc
```

Similar to https://github.com/Kudo/react-native-v8/issues/2?

**Comment by Kudo** [comment]
Thanks for reporting this. Do you have any reproduced steps and code? The would be helpful to troubleshoot.

**Comment by Kudo** [comment]
Hey, do you have any updates for this? I am looking forward to solving this issue.

**Comment by bhaskarGyan** [comment]
@Kudo , @smacgregor , we faced a similar issue with exactly the same stack trace. In our case, we were sending a huge amount of data as a Object from js to native layer via the bridge(same is working with Hermes and JSC). As a workaround, for now, we are sending the data as a String and converting it back to Object at the Native layer.

I will try to share code example replicating the issue over the weekend

**Comment by smacgregor** [comment]
Sorry for not giving you more information - we've been experimenting with Hermes as well. We do make heavy use of the bridge as we are a brown field app so @bhaskarGyan could be onto something.

**Comment by Kudo** [comment]
Thank you @bhaskarGyan and @smacgregor.
These information are great for troubleshooting.
After re-evaluating the crash backtrace, The call flow might come from `nativeFlushQueueImmediate` and it might be my fault to do JSI hosted function incorrectly.
 Will try to reproduce the crash and fix it as well.

**Comment by Kudo** [comment]
Unfortunately, I still cannot reproduce the crash for JS -> Native call.
Could you reproduce the issue for debug build?

On the other hand, a trick is to log the parameter of `nativeFlushQueueImmediate` and see if there are something special to trigger the crash.
Edit `node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js` and add
`console.log('ooxx queue', JSON.stringify(queue));` before the line of `global.nativeFlushQueueImmediate(queue);`

**Comment by Kudo** [comment]
@rawrmaan Awesome! I will try the steps later and see if I could reproduce and fix the problem hopefully.

**Comment by bhaskarGyan** [comment]
@Kudo, was a little busy so I was not able to follow up on this. I tried logging the error. PRIVATE_DATA is basically a 1D array of the data which I am passing through the bridge. 

'ooxx queue', '[[16,3],[5,1],[[[[ **PRIVATE_DATA**]]]]'

**Comment by Kudo** [comment]
I could reproduce the crash by a simple native ViewManager and passing the `propBCrashing` as @rawrmaan provided. Thank you all and I could further going to the native debugging and try to find out what's going wrong.  🔥

**Comment by Kudo** [comment]
The root cause should be the numeric object property, #15 is addressing the issue.
Will do some test for the fix and hopefully to release a new version tomorrow.
Thank you to provide helpful information and make RNV8 better.

**Comment by Kudo** [comment]
Publish react-native-v8 `0.59.10-patch.2`, `0.60.4-patch.2`, `0.60.5-patch.0` which all include #15 fix.
Please choose a version to see if the new version did help for the issue.
Thanks for all your help.

**Comment by bhaskarGyan** [comment]
@Kudo , Thanks.

Working for me with 0.60.4-patch.2
