### ISSUE TITLE
debug ,global._v8runtime is not a function

### ISSUE THREAD

**Issue by HeartWalker** [Kudo/react-native-v8#11]
when i use Debug JS Remote, global._v8runtime is not a function,
if i close, it's ok

**Comment by Kudo** [comment]
@HeartWalker Remote debugging in fact runs JS engine in your hosted Chrome, not the V8 on device, so that `global._v8runtime` is undefined.

**Comment by Kudo** [comment]
I am getting to close this issue. Please feel free to let me know if there are any further problems.

**Comment by HeartWalker** [comment]
> I am getting to close this issue. Please feel free to let me know if there are any further problems.



> @HeartWalker Remote debugging in fact runs JS engine in your hosted Chrome, not the V8 on device, so that `global._v8runtime` is undefined.



> @HeartWalker Remote debugging in fact runs JS engine in your hosted Chrome, not the V8 on device, so that `global._v8runtime` is undefined.



> @HeartWalker Remote debugging in fact runs JS engine in your hosted Chrome, not the V8 on device, so that `global._v8runtime` is undefined.

thanks, you are right, i found this in the documentation.  so i suggest you modify readme

**Comment by Kudo** [comment]
Added some note at README, thank you.
