### ISSUE TITLE
 Syntax error in cmake code when parsing string

### ISSUE THREAD

**Issue by devoren** [Kudo/react-native-v8#119]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-v8:generateJsonModelDebug'.
> C:\...\app\node_modules\react-native-v8\android\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error at C:\...\app\node_modules\react-native-v8\android\CMakeLists.txt:117 (add_library):
    Syntax error in cmake code when parsing string
      C:\...\app\node_modules\react-native/ReactCommon/jsiexecutor/jsireact/JSIExecutor.cpp;C:\...\app\node_modules\react-native/ReactCommon/jsiexecutor/jsireact/JSINativeModules.cpp
    Invalid character escape '\w'.
    
    "react-native": "0.67.2",
    "react-native-v8": "1.2.0",
    "v8-android-jit-nointl": "^10.100.0"
    
    **Do you know how to solve it?**

**Comment by Kudo** [comment]
duplicated as #115. i'll update in #115 when there's a fix. thanks!
