### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by vbylen** [Kudo/react-native-v8#123]
I'm on expo v45 and get this when building the dev client through eas

```bash
[stderr] 
FAILURE: Build failed with an exception.
[stderr] 
* What went wrong:
[stderr] 
Execution failed for task ':app:mergeDebugNativeLibs'.
[stderr] 
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
[stderr] 
   > 2 files found with path 'lib/arm64-v8a/libjsinspector.so' from inputs:
[stderr] 
      - /home/expo/workingdir/build/node_modules/react-native-v8/android/build/intermediates/library_jni/debug/jni/arm64-v8a/libjsinspector.so
[stderr] 
      - /home/expo/.gradle/caches/transforms-3/7d9d92dc8ec1ba2e45aff2ecbb549550/transformed/jetified-react-native-0.68.2/jni/arm64-v8a/libjsinspector.so
[stderr] 
     If you are using jniLibs and CMake IMPORTED targets, see
[stderr] 
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets
[stderr] 
```

**Comment by vbylen** [comment]
Thanks!

On opening the dev client I'm now getting the error `couldn't find DSO to load libhermes.so`

I already made sure to set `jsEngine` to "jsc".

Any ideas how to fix it?

**Comment by vbylen** [comment]
@Kudo the error disappears when I set jsEngine to "hermes". But then the engine is running on hermes and not v8.

Is maybe one of the libraries I'm using not supported?

**Comment by Kudo** [comment]
it looks like expo-dev-client doesn't support other js engines. i'll add a task in expo internally. hopefully we can address the problem in next expo sdk.

**Comment by roadmanfong** [comment]
Hi I just got into libhermes.so situation for expo-dev-client, is there any updates? thank you.

**Comment by Kudo** [comment]
fyi! expo-dev-client@1.3.0 + react-native-v8@1.5.0 should be compatible now.
