### ISSUE TITLE
Build-in polyfills or transformed features out of box

### ISSUE THREAD

**Issue by retyui** [Kudo/react-native-v8#127]
I worked on table https://retyui.github.io/react-native-compat-table/ to compare JS features/engines

And found out, that some of them not available:

- `Promise.any` // TypeError: Promise.any is not a function
- `Promise.allSettled` // TypeError: Promise.allSettled is not a function

> React Native use a [`promise`](https://github.com/facebook/react-native/blob/3da3d82320bd035c6bd361a82ea12a70dba4e851/Libraries/Promise.js#L13) module

---

- async generator `async function* () { ... }`
- async iterable `for await (let value of range) { ... }` // TypeError: Invalid attempt to iterate non-iterable instance. In order to be iterable, non-array objects must have a `[Symbol.iterator]()` method.

> By default used a [`metro-react-native-babel-preset`](https://github.com/facebook/metro/blob/aeb6f4f6ceed239f589b5994b10b7ab12aa80a79/packages/metro-react-native-babel-preset/src/configs/main.js#L119-L124)

**Comment by Kudo** [comment]
hi there! as you mentioned, even v8 supports native Promise, react-native will still [polyfill Promise](https://github.com/facebook/react-native/blob/e0a71fc7b5cb8c264000147099be5b2575931193/Libraries/Core/polyfillPromise.js#L25-L38). how did you verify the Promise supportness for v8?

btw, the comparison looks promising. great job 🤩

**Comment by retyui** [comment]
not relevant any more
