### ISSUE TITLE
Run code directly from dev server cause Non-Ascii characters garbled

### ISSUE THREAD

**Issue by ITJesse** [Kudo/react-native-v8#13]
![image](https://user-images.githubusercontent.com/3601376/63077541-985eba80-bf73-11e9-9545-a172c1041336.png)

**Comment by RageBill** [comment]
I have the same problem when running in dev environment. However, once I have my debugger turned on, the app runs normally. This is a very weird error regarding Non-ASCII characters.

**Comment by ITJesse** [comment]
@RageBill When you turn the debugger on, the code is running on the debugger, not on your phone.

**Comment by Kudo** [comment]
@ITJesse For the broken text, do you have any special properties, like custom font?
How about to share some code here?
E.g.
```js
<Text style={{ fontSize: 24 }}>Non-ASCII, e.g. 天気</Text>
```

And it looks like the text on your UI bottom sheet is correct, what is the difference between these text?

At last, what is the React Native version you used?

**Comment by ITJesse** [comment]
@Kudo I am using styled-components for styling.
The bottom sheet is a part of native, not RN.

React Native: 0.59.10

**Comment by ITJesse** [comment]
I can confirm that every Non-ASCII character is broken.

**Comment by Kudo** [comment]
I've tried on 0.59.10 but works for me.
Let me try styled-components.

**Comment by Kudo** [comment]
@ITJesse 
This works for me.

```js
import styled from 'styled-components/native';

const StyledText = styled.Text`
  color: palevioletred;
`;

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        <StyledText>天気</StyledText>
      </View>
    );
  }
}
```

**Comment by RageBill** [comment]
Not sure if it helps, in my scenario, it works fine on my production build and on React Native Debugger. However, it just doesn't work on development build on my Android emulator. The broken characters are Chinese and they were returned from an API call.

My RN version is 0.60.4 and my Android emulator is API 26 Nexus 5X.

**Comment by ITJesse** [comment]
@Kudo Thanks for your help. I will do more tests on how to reproduce this problem this weekend.

**Comment by Kudo** [comment]
I've also tested an API returned text and seems works for me.
Looking forward to seeing if there are reproducible test cases.

```js
const StyledText = styled.Text`
  color: palevioletred;
  font-size: 24px;
`;

type Props = {};
export default class App extends Component<Props> {
  state = {
    text: '',
  };

  componentDidMount() {
    fetch(
      'https://postman-echo.com/get?text=%E4%B8%AD%E6%96%87%E5%A4%A9%E6%B0%97',
    )
      .then(resp => resp.json())
      .then(resp => {
        this.setState({text: resp.args.text});
      });
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>
          {global._v8runtime != null ? global._v8runtime().version : 'Not V8'}
        </Text>
        <StyledText>{this.state.text}</StyledText>
      </View>
    );
  }
}
```

**Comment by ITJesse** [comment]
I still cannot figure out why the Non-Ascii is broken in some of my projects.
I will close this issue now, and keep update if I found the reason.

**Comment by t0m0120** [comment]
@ITJesse 

Only debugging is same issue.

Template literal may be the cause.

```
const Text = styled.text``

<Text>{`日本語テキスト\n↑JapaneseText`}</Text> // garbled 
<Text>日本語テキスト\n↑JapaneseText</Text> // good
```

| template literals | not template literals |
| --- | --- |
|![image](https://user-images.githubusercontent.com/34805701/63337285-af3e4c00-c37b-11e9-8bdf-abed13a4fde0.png) | ![image](https://user-images.githubusercontent.com/34805701/63337306-b9f8e100-c37b-11e9-8c4f-4e263fe54bcb.png) |

**Comment by Kudo** [comment]
Thanks @t0m0120, but I am still unable reproduce the problem even for template literal.

Let's trying to dig out more information.
1. Is the problem reproducible on Android emulator or only on real device?
2. What's your Android system language?
3. What's is your react-native version and react-native-v8 version? Please check the real version from yarn.lock.
3. On the same device which had the problem, could you reproduce the problem for a simple test case?
    E.g. `react-native init RN059 --version react-native@^0.59.10`,  adding react-native-v8 and use my sample code above.
4. Verify the text from bundle, is the text a normal UTF-8 text? (Download bundle from `wget 'http://localhost:8081/index.bundle?platform=android&dev=true&minify=false'`)

@ITJesse As there are people reported such problems, I am going to leave this issue opened and hopefully we could find the root cause and fix it.

**Comment by t0m0120** [comment]
@Kudo 
try 0.59.10-patch.2
No longer garbled in debug mode
Thank you !!

**Comment by Kudo** [comment]
@t0m0120 Awesome! Thanks for your confirmation.

**Comment by ITJesse** [comment]
@Kudo Thanks for your awesome work!
