### ISSUE TITLE
Invalid character escape '\C'.

### ISSUE THREAD

**Issue by aleluiah** [Kudo/react-native-v8#130]
Execution failed for task ':react-native-v8:configureCMakeRelWithDebInfo[arm64-v8a]'.
> [CXX1405] error when building with cmake using C:\project\node_modules\react-native-v8\android\CMakeLists.txt: Build command failed.
  Error while executing process C:\Program Files\CMake\bin\cmake.exe with arguments {-HC:\project\node_modules\react-native-v8\android -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=21 -DANDROID_PLATFORM=android-21 -DANDROID_ABI=arm64-v8a -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=C:\android-ndk-r22b -DCMAKE_ANDROID_NDK=C:\android-ndk-r22b -DCMAKE_TOOLCHAIN_FILE=C:\android-ndk-r22b\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Program Files\CMake\bin\ninja.exe -DCMAKE_CXX_FLAGS=-fstack-protector-all -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\project\node_modules\react-native-v8\android\build\intermediates\cxx\RelWithDebInfo\2e1b1q1t\obj\arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=C:\project\node_modules\react-native-v8\android\build\intermediates\cxx\RelWithDebInfo\2e1b1q1t\obj\arm64-v8a -DCMAKE_BUILD_TYPE=RelWithDebInfo -BC:\project\node_modules\react-native-v8\android\.cxx\RelWithDebInfo\2e1b1q1t\arm64-v8a -GNinja -DANDROID_STL=c++_shared -DBOOST_VERSION=1_76_0 -DBUILD_DIR=C:\project\node_modules\react-native-v8\android\build -DRN_DIR=C:\project\node_modules\react-native -DREACT_NATIVE_TARGET_VERSION=69 -DV8_ANDROID_DIR=C:\project\node_modules\v8-android-jit-nointl -DSO_DIR=C:\Cliqueon\node_modules\react-native-v8\android\build/jniLibs}
  -- The C compiler identification is Clang 11.0.5
  -- The CXX compiler identification is Clang 11.0.5
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: C:/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring incomplete, errors occurred!
  See also "C:/project/node_modules/react-native-v8/android/.cxx/RelWithDebInfo/2e1b1q1t/arm64-v8a/CMakeFiles/CMakeOutput.log".

  CMake Error at CMakeLists.txt:131 (add_library):
    Syntax error in cmake code when parsing string

      C:\project\node_modules\react-native/ReactCommon/jsiexecutor/jsireact/JSIExecutor.cpp;C:\Cliqueon\node_modules\react-native/ReactCommon/jsiexecutor/jsireact/JSINativeModules.cpp

    Invalid character escape '\C'.

  CMake Error at CMakeLists.txt:131 (add_library):
    Syntax error in cmake code when parsing string

      C:\project\node_modules\react-native/ReactCommon/reactperflogger/reactperflogger/BridgeNativeModulePerfLogger.cpp
    Invalid character escape '\C'.

  CMake Error at CMakeLists.txt:131 (add_library):
    Syntax error in cmake code when parsing string

      C:\project\node_modules\react-native/ReactCommon/cxxreact/JSExecutor.cpp

    Invalid character escape '\C'.

ndk version is r22b

**Comment by aleluiah** [comment]
seems like some cmake environment variables are improperly expanded

**Comment by devoren** [comment]
duplicated as #115, its bug

**Comment by Kudo** [comment]
duplicated issue as #115
