### ISSUE TITLE
Invalid character escape '\R'.

### ISSUE THREAD

**Issue by vijaydvk** [Kudo/react-native-v8#131]
Execution failed for task ':react-native-v8:configureCMakeDebug'.
> C/C++: D:\Reactnative\Projects\Live\wasteoftime\node_modules\react-native-v8\android\CMakeLists.txt debug|armeabi-v7a : CMake Error at D:\Reactnative\Projects\Live\wasteoftime\node_modules\react-native-v8\android\CMakeLists.txt:131 (add_library):
    Syntax error in cmake code when parsing string

      D:\Reactnative\Projects\Live\wasteoftime\node_modules\react-native/ReactCommon/jsiexecutor/jsireact/JSIExecutor.cpp;D:\Reactnative\Projects\Live\wasteoftime\node_modules\react-native/ReactCommon/jsiexecutor/jsireact/JSINativeModules.cpp

    Invalid character escape '\R'.

**Comment by Kudo** [comment]
duplicated issue as #115
