### ISSUE TITLE
RUNTIMEEXECUTOR_LIB set to NOTFOUND

### ISSUE THREAD

**Issue by gmaclennan** [Kudo/react-native-v8#149]
I am using react-native v0.66.5. I just updated to react-native-v8@1.5.2 from react-native-v8@0.66.3-patch.1 (because I was getting a v8 runtime error the update from react-native v0.66.4 to v0.66.5).

I am now getting a build error from gradle:

```
* What went wrong:
Execution failed for task ':react-native-v8:generateJsonModelDebug'.
> ./node_modules/react-native-v8/android/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  RUNTIMEEXECUTOR_LIB
      linked by target "v8executor" in directory ./node_modules/react-native-v8/android
```

Google searches seem to return nothing for `RUNTIMEEXECUTOR_LIB`, so I'm not sure where to go next.

**Comment by gmaclennan** [comment]
In case this is also useful information:

```
ls -Ral node_modules/react-native/ReactCommon/runtimeexecutor
.rw-r--r--   41 user 26 Oct  1985 .clang-tidy
.rw-r--r--  502 user 26 Oct  1985 Android.mk
.rw-r--r-- 1.4k user 26 Oct  1985 BUCK
.rw-r--r-- 1.4k user 26 Oct  1985 React-runtimeexecutor.podspec
drwxr-xr-x    - user  7 Nov 10:18 ReactCommon/

node_modules/react-native/ReactCommon/runtimeexecutor/ReactCommon:
.rw-r--r-- 3.9k user 26 Oct  1985 RuntimeExecutor.h
```

**Comment by gmaclennan** [comment]
Minimal reproduction here: https://github.com/gmaclennan/RnTest_0_66_5

**Comment by gmaclennan** [comment]
Further info: In a minimal repro, everything works fine with react-native-v8@1.4.8, so this seems like a recently introduced change likely related to #144 and #145.

**Comment by Kudo** [comment]
sorry for the breaking change. just notice the runtimeexecutor was not a shared library until react-native 0.68. will have a fix this week.

**Comment by Kudo** [comment]
react-native-v8@1.6.0 includes #154 and should fix the problem for you. thanks for reporting this issue.
