### ISSUE TITLE
react-native change maven center from November 4th 2022.

### ISSUE THREAD

**Issue by wangchongwei** [Kudo/react-native-v8#153]
Hello,

https://github.com/facebook/react-native/issues/35210

react-native: 0.59.10
react-native-v8: ^0.59.10-patch.6
implementation 'org.chromium:v8-android:8.80.+'

when react-native change maven center from November 4th 2022.

i update android/build.gradle:

```
configurations.all {
        resolutionStrategy {
            force "com.facebook.react:react-native:0.59.10"  //<-- please change here
        }
    }
```
build success, but app start, get error :
   java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so caused by: dlopen failed: library "libjsc.so" not found

i need some help

**Comment by capezzbr** [comment]
Run

`rm -rf node_modules/react-native-v8/android/build` then cd into your Android app directory and run `./gradlew extractSOFiles`

**Comment by wangchongwei** [comment]
@capezzbr 
thank you.
but i use react-native-v8 version : ^0.59.10-patch.6
react-native: 0.59.10

1、`node_modules/react-native-v8/`  folder android does not exist
2、`run ./gradlew extractSOFiles`   Task 'extractSOFiles' not found in root project '***'



What other work can I do, can you give me some advice？
thank you again.

**Comment by Kudo** [comment]
@wangchongwei the https://github.com/facebook/react-native/issues/35210 should be resolved even without the android/build.gradle. could you try to remove the patch and try again?

**Comment by wangchongwei** [comment]
@Kudo 
thank you.
i tried.
but when i remove v8, the jsc error show again.

in last year, i found some jsc error  by firebase, then i know react-native-v8, and i use it.

It solved the problem perfectly.

But now, they can't work together

thank you again.

**Comment by Kudo** [comment]
i am not quite understanding your problem. do you mean which two modules cannot work together, jsc + v8 or firebase + v8? if you have some minimal reproducible example, i could help to further investigate.

**Comment by SmirnovM91** [comment]
+

**Comment by Kudo** [comment]
hi there! i'm closing this as the react-native artifact should be removed from maven central. if someone still encounter the problem, please let me know. thanks!
