### ISSUE TITLE
Incorrect version number in 10.100.1

### ISSUE THREAD

**Issue by matias-la** [Kudo/react-native-v8#158]
The `v8-android@10.100.1` NPM package ships the following files:

```
dist/org/chromium/v8-android/10.100.0/v8-android-10.100.0.pom.sha1
dist/org/chromium/v8-android/10.100.0/v8-android-10.100.0.aar.sha1
dist/org/chromium/v8-android/10.100.0/v8-android-10.100.0.aar
dist/org/chromium/v8-android/10.100.0/v8-android-10.100.0.pom.md5
dist/org/chromium/v8-android/10.100.0/v8-android-10.100.0.aar.md5
dist/org/chromium/v8-android/10.100.0/v8-android-10.100.0.pom
```

It looks like the version numbers weren't updated, so it says `10.100.0` instead of `10.100.1`. Would it be possible to fix this issue so the version numbers in NPM metadata and package filenames are consistent?

**Comment by Kudo** [comment]
i'm sorry this issue my mistake when publishing v8-android. will fix this in the next v8-android v11.

**Comment by Kudo** [comment]
the latest v8-android fixed the issue. thanks for reporting the issue!
