### ISSUE TITLE
unicode variable names issue

### ISSUE THREAD

**Issue by mmerickel** [Kudo/react-native-v8#16]
I think my issue is close enough to #14 that it's the same but it's in the code and not in the display.

We used react-native-v8 happily on one project, and so I started updating another one to use it today. Reproducible issue in the emulator is that it cannot parse our code which has a few unicode variable names in it. I can confirm that the bundle loaded from wget looks normal when opened as utf8. This is using react-native@0.60.4 with react-native-v8@0.60.4-patch.1 and v8-android@7.5.1.

```js
const R = {
  miles: 3959,
  km: 6371,
};

class Geolocation {
  constructor(lat, lon) {
    this.latitude = lat;
    this.longitude = lon;
  }
  distanceTo(lat, lon, unit = 'miles') {
    const φ1 = this.latitude * Math.PI / 180.0;
    const λ1 = this.longitude * Math.PI / 180.0;
    const φ2 = lat * Math.PI / 180.0;
    const λ2 = lon * Math.PI / 180.0;
    const Δφ = φ2 - φ1;
    const Δλ = λ2 - λ1;

    const a = Math.sin(Δφ / 2) * Math.sin(Δφ / 2)
              + Math.cos(φ1) * Math.cos(φ2)
              * Math.sin(Δλ / 2) * Math.sin(Δλ / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

    return R[unit] * c;
  }
}
```

<img width="604" alt="Screen Shot 2019-08-28 at 12 14 12 PM" src="https://user-images.githubusercontent.com/487237/63877510-609d3d00-c98d-11e9-95f0-e1850f47e8ce.png">

**Comment by mars-lan** [comment]
Can you give release build a try?

**Comment by Kudo** [comment]
Publish react-native-v8 `0.59.10-patch.2`, `0.60.4-patch.2`, `0.60.5-patch.0` which all include #17 fix.
Please choose a version to see if the new version did help for the issue.
Thanks for all your help.

**Comment by mmerickel** [comment]
I can confirm this fixes the variable names issue for me. Thanks for the quick turn around @Kudo!
