### ISSUE TITLE
Super slow boost download

### ISSUE THREAD

**Issue by reinismu** [Kudo/react-native-v8#160]
It takes around 2 hours for it to download every time I build...

![image](https://user-images.githubusercontent.com/35471680/211547336-49276872-20de-48e4-a700-1c85f44745a6.png)

Has anyone noticed this as well? Is there a way to change url where it is downloading it from?

**Comment by Kudo** [comment]
hi there! i'm sorry this would be an known issue. you could add `REACT_NATIVE_DOWNLOADS_DIR` environment variable to some local path for keeping the boost tarball, next time gradle will not download it again when cache hit. i.e.
`REACT_NATIVE_DOWNLOADS_DIR=$HOME/REACT_NATIVE_DOWNLOADS_DIR ./gradlew :app:assembleDebug`

**Comment by reinismu** [comment]
Why is it not cached by default? I'm pretty sure CMake can do that
