### ISSUE TITLE
Any plans for snapshot and code caching?

### ISSUE THREAD

**Issue by arasrezaei** [Kudo/react-native-v8#163]
Hi there,
Thanks for your efforts,
I think this engine is wayyyy better then Hermes in almost any aspect.
I saw you from a conference used snapshot and code caching with this engine.
The results were very exciting!
I wonder when will this great features be available? Are there any plans for it?

And updating the results of engines to latest version of them will be really good. Please update them 🙏

**Comment by Kudo** [comment]
hi there!

i've added the standard bytecode caching and v8 11 in react-native-v8 2.1. please let me know whether it works for you. thanks a lot.
