### ISSUE TITLE
Expo sdk 48 error

### ISSUE THREAD

**Issue by arasrezaei** [Kudo/react-native-v8#168]
hello,
got this error on dev client build on eas develpment build:
`
> Task :react-native-v8$expo:compileDebugJavaWithJavac FAILED
[stderr] 
/home/expo/workingdir/build/node_modules/react-native-v8/expo/src/main/java/io/csie/kudo/reactnative/v8/expo/V8ExpoAdapterPackage.java:31: error: cannot find symbol
[stderr] 
                final String v8BundleAssetName = V8ExecutorFactory.getBundleAssetName(context, useDeveloperSupport);
[stderr]                                                            
[stderr] 
  symbol:   method getBundleAssetName(Context,boolean)
[stderr] 
  location: class V8ExecutorFactory
[stderr] 
1 error
`

v2.1.1

**Comment by sunnylqm** [comment]
https://github.com/Kudo/react-native-v8/commit/3380d22428020f28cdab6d8620f9c3f740baa518#diff-c57a039bff89809fade81cfbf23da39e64e5412f5b4d37a9bb82f865bb3a15daR71
https://github.com/Kudo/react-native-v8/blob/0462d2abde60e47076cd3a865ca23f2de4ff8d38/expo/src/main/java/io/csie/kudo/reactnative/v8/expo/V8ExpoAdapterPackage.java#L31

**Comment by Kudo** [comment]
thanks for reporting the issue. the issue should be resolved by `react-native-v8@2.1.2`
