### ISSUE TITLE
This react-native-v8 version only supports react-native>=0.71.0

### ISSUE THREAD

**Issue by wangchongwei** [Kudo/react-native-v8#174]
react-native version: 0.69.7

how can i use react-native-v8?

i see : https://github.com/Kudo/react-native-v8/blob/1.0-stable/README.md

but get error: This react-native-v8 version only supports react-native>=0.71.0

**Comment by Kudo** [comment]
hi there! you should use `react-native-v8@1.6.0`. let me know if it doesn't work for you. thanks!
