### ISSUE TITLE
[0.72] Build error in android

### ISSUE THREAD

**Issue by NiuGuohui** [Kudo/react-native-v8#175]
**Package info:**
    "react-native": "0.72.0-rc.1",
    "react-native-v8": "^2.1.3",
    "v8-android-jit-nointl": "^11.110.1"

ndkVersion = "24.0.8215888"

**Build console output:**
Task :react-native-v8:buildCMakeDebug[arm64-v8a][v8executor] FAILED

`In file included from xxxx/node_modules/react-native-v8/src/v8runtime/JSIV8ValueConverter.cpp:8:`
`In file included from xxxx/node_modules/react-native-v8/src/v8runtime/JSIV8ValueConverter.h:10:`
`xxxx/node_modules/react-native-v8/src/v8runtime/V8Runtime.h:156:42: error: non-virtual member function marked 'override' hides virtual member functions`

**Comment by NiuGuohui** [comment]
@Kudo Hello, can you take a look at this question?

**Comment by NiuGuohui** [comment]
I fixed it. #176

**Comment by valeshgopal** [comment]
I am having the same error `Task :react-native-v8:buildCMakeDebug[v8executor] FAILED` in react native 0.68.2. Is there a fix for it as well?

**Comment by Kudo** [comment]
the 0.72.0 support is resolved by react-native-v8@2.2.0. thanks!
