### ISSUE TITLE
_v8runtime() function not available

### ISSUE THREAD

**Issue by tijs** [Kudo/react-native-v8#18]
I have followed the instructions to replace JSC with V8 but when i try to verify that it worked using the method from the README i get an error that the _v8runtime() function does not exist.

e.g.

`console.log(`V8 version is ${global._v8runtime().version}`);`

When i unzip the APK though i can cleary see that the jsc.so file is no longer there and instead it has the jsV8.so library. Is the _v8runtime() method not always availble?

**Comment by Kudo** [comment]
@tijs `global._v8runtime` will not exist if you enable RN's remote debugging mode.
Did you enable remote debugging mode?

**Comment by tijs** [comment]
Ah yes of course! Thanks forgot about that.
