### ISSUE TITLE
Non-virtual member function marked 'override' hides virtual member functions

### ISSUE THREAD

**Issue by Satishpethani92** [Kudo/react-native-v8#181]
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__memory/unique_ptr.h:714:32 Allocating an object of abstract class type 'rnv8::V8Runtime'

**Comment by Kudo** [comment]
hi there! if you have react-native 0.72, please try out react-native-v8@2.2.0. thanks!
