### ISSUE TITLE
Using it on React 0.59.10

### ISSUE THREAD

**Issue by oximer** [Kudo/react-native-v8#19]
Could you help me to understand how to migrate my project using 0.59.10 to V8?

**Comment by oximer** [comment]
I managed to make it.

**Comment by Kudo** [comment]
Nice, please let me clarify one more time that 0.59.19 is supported.
`yarn add 'react-native-v8@>=0.59.10-patch.0 <0.59.11'`
And I am going to close this issue. feel free to open new one if you have any other questions.
