### ISSUE TITLE
App bloated

### ISSUE THREAD

**Issue by leonardo2204** [Kudo/react-native-v8#20]
Hi @Kudo!
First of all, thanks for the hard work put into this excellent library!
After building my app to production (bundle release), I realized that my APK size increased by more than 159% (even google store gave me this warning).
AFAIK Hermes decreases the size of the APK, where V8 is (highly) increasing it. Is that supposed to happen or have I missed something when configuring it?

Thanks for reading and helping me!

**Comment by Kudo** [comment]
Currently I have enabled Intl support in V8 so that the size will increase about 7MB per ABI.
If the size is a concern, I could have an option to pack non-Intl version.
However, I think the size is not comparable to Hermes.

**Comment by leonardo2204** [comment]
From what I know, intl in V8 helps with date formatting, pluralization and number formatting right?
My only concern is how turning this off (or a opt-out) would impact any RN app that uses this kind of thing. Any thoughts on this?
But 7mb is a huge number anyways...

Thanks again

**Comment by Kudo** [comment]
Well, default JSC and Hermes does not have Intl support.
To have Intl, JSC needs to [modify some configuration in RN](https://github.com/react-native-community/jsc-android-buildscripts#international-variant).

My approach on the other hand is to have Intl support by default.
If APK size is a concern, user could choose no Intl variant.

**Comment by leonardo2204** [comment]
Hmm I see, it seems that having both options (with/out) is the best scenario. Also, adding this to the docs (just like the link you provided) would be cool.
Thanks for clarifying this and taking your time!
I'll wait for the no-intl version, once it comes out I'll let you know how lighter the apk got ;)

**Comment by Kudo** [comment]
no Intl version is completed, please check the setup guide at https://github.com/Kudo/react-native-v8/blob/master/README.md#how-to-reduce-apk-size-

I also have a [APK size comparison](https://docs.google.com/spreadsheets/d/1uce3WZ9IaAEUu6Owj3eXEuZb25PDi6ZcgUVV2i500S0/edit#gid=246943941), take a look if it helps.

**Comment by leonardo2204** [comment]
@Kudo Cool, as soon as I get home I'll test and let you know!
Really appreciate all the hard work put into this!

**Comment by Kudo** [comment]
Thanks and feel free to let me know if you have any further questions.
