### ISSUE TITLE
did support force collect garbage api

### ISSUE THREAD

**Issue by binlaniua** [Kudo/react-native-v8#21]
like , window.gc()

**Comment by binlaniua** [comment]
perhaps how to set jsHeaperLimit

**Comment by Kudo** [comment]
V8 controls GC scheduling itself.
There is a API `RequestGarbageCollectionForTesting ` to request GC but is only for testing purpose.
https://chromium.googlesource.com/v8/v8.git/+/7.5.288.23/include/v8.h#8153

I am afraid to say that the feature is not officially supported in the mean time.
You may able to have a [custom V8 build](https://github.com/Kudo/v8-android-buildscripts) if you still need some alternatives.

**Comment by binlaniua** [comment]
thanks
