### ISSUE TITLE
Using with forked React-Native

### ISSUE THREAD

**Issue by Gutyn** [Kudo/react-native-v8#23]
Is there any way to use this with a forked react-native? So I could just hook it into v8-android?

**Comment by Kudo** [comment]
I don't have easy solution either.

react-native-v8 is simply [v8runtime implementation](https://github.com/Kudo/react-native-v8/tree/master/v8runtime) + [RN build scripts patch](https://github.com/Kudo/react-native-v8/tree/master/patches).
You may able to reference the v8runtime code by git submodule in your forked repo.

**Comment by Kudo** [comment]
I am going to close this issue, please feel free to let me know if you have any further questions.

**Comment by Gutyn** [comment]
Thank you @Kudo , I was able to fork this repo and point to my RN fork.

**Comment by Gutyn** [comment]
The newest v8 with rn 63 results in:

```
make: Leaving directory '/Users/mihail/Documents/workspace/react-native-v8/build/ReactAndroid/src/main/jni/react/jni' |  
-- | --
  | return int(wrapNoInt(open, name, flags, mode)); |  
  | ^~~~~~~~~ |  
  | /Users/mihail/Documents/workspace/react-native-v8/build/ReactAndroid/build/third-party-ndk/folly/folly/detail/FileUtilDetail.h:34:9: note: candidate template ignored: couldn't infer template argument 'F' |  
  | ssize_t wrapNoInt(F f, Args... args) { |  
  | ^ |  
  | 1 error generated. |  
  | make: *** [/Users/mihail/Library/Android/sdk/ndk/21.3.6528147/build/core/build-binary.mk:478: /Users/mihail/Documents/workspace/react-native-v8/build/ReactAndroid/build/tmp/buildReactNdkLib/local/armeabi-v7a/objs/folly_json/folly/FileUtil.o] Error 1 |  
  | make: *** Waiting for unfinished jobs....


```

Have you seen this @Kudo ?

**Comment by Gutyn** [comment]
@Kudo I am sorry for bothering you with this, I understand that this repo is not intended for my use case but please tell me just one thing, how do you build it? I am going crazy here.

**Comment by Kudo** [comment]
@Gutyn react-native-v8 for Android build is like what RN Android did - by the [build.gradle](https://github.com/facebook/react-native/blob/0.63-stable/ReactAndroid/build.gradle), [Application.mk](https://github.com/facebook/react-native/blob/0.63-stable/ReactAndroid/src/main/jni/Application.mk) and some Android.mk.

react-native-v8 did some patches for existing build.gradle and Android.mk to make V8Runtime.
You could reference CI build script for a reference. https://github.com/Kudo/react-native-v8/blob/master/.circleci/config.yml

Your error seems coming from Folly.
Could you double check if you could build RN successfully without react-native-v8?

**Comment by Gutyn** [comment]
@Kudo ok thank you very much, will try building rn without v8!

**Comment by Gutyn** [comment]
Was able to figure it out, THANK YOU @Kudo for this package and all your hard work. Will try not to bother you too often :)
