### ISSUE TITLE
Support for RN 0.61

### ISSUE THREAD

**Issue by gpawlik** [Kudo/react-native-v8#24]
Version `0.61` of React Native has just been released, could you tell me when can we expect a release of a compatible version of `react-native-v8`? Thanks!

**Comment by gedeagas** [comment]
+1

**Comment by Kudo** [comment]
Published [v0.61.1-patch.0](https://www.npmjs.com/package/react-native-v8/v/0.61.1-patch.0).
Please let me know if you are sticked on RN 0.61.0 (not 0.61.1) and need the `react-native-v8@0.61.0-patch.0`

**Comment by shaunsc** [comment]
Awesome! Thanks @Kudo

**Comment by gpawlik** [comment]
`0.61.1` is ok, thank you @Kudo 🙂
