### ISSUE TITLE
JS Date timezone off for Australia/Melbourne

### ISSUE THREAD

**Issue by svenlombaert** [Kudo/react-native-v8#37]
When I put my phone in timezone `Australia/Melbourne` and I execute:
```javascript
Alert.alert(new Date().toString());
```

I get this as output: `Fri Jan 17 2020 22:31:39 GMT+1000 (GMT+10:00)`. 
Actually, Melbourne is currently in GMT+11 due to daylight savings time (https://time.is/Melbourne).

When remote debugging is **on**, I do get the correct timezone, as well as on iOS. This leads me to think it might be an issue with react-native-v8.

**Comment by mcuelenaere** [comment]
In the latest Chrome browser (also using the V8 engine), this [JSFiddle](https://jsfiddle.net/b53zcuLs/) shows the correct timezone (GMT+11).

**Comment by Kudo** [comment]
@svenlombaert Did you use Intl or no Intl version of v8-android?

**Comment by svenlombaert** [comment]
We use the Intl version

**Comment by svenlombaert** [comment]
@Kudo any ideas on this?

**Comment by Kudo** [comment]
Sorry for late response.
I found that is in fact a V8 + ICU integration issue.
Opening a discussion at V8 mailing list: https://groups.google.com/forum/#!topic/v8-dev/vuKkY76fBXo
Hopefully the problem could be fixed from V8.

**Comment by Kudo** [comment]
Well, I've patched V8 to support passing timezone anyway.
Could you please test v0.61.5-patch.3 (with v8-android-* 8.80.1) and see if the version fixed your problem?

**Comment by Kudo** [comment]
I am going to close this issue as the problem may be fixed.
Please feel free to open again if the new version did not help.

**Comment by bluesky950520** [comment]
Ok this project is good
