### ISSUE TITLE
Can we use V8 remote debugging in this project?

### ISSUE THREAD

**Issue by anchengjian** [Kudo/react-native-v8#40]
In RN remote debugging mode, JS code is still running in chrome. But in this project, V8 is running on the mobile device, so can we use V8 remote debugging in this project?

Similar to https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews

**Comment by haozhutw** [comment]
What is the answer here? why close? @anchengjian Could you please share your findings? I want to know if we can still debug with chrome after integrating `react-native-v8`, thanks.
