### ISSUE TITLE
nointl module not found for 0.61.5

### ISSUE THREAD

**Issue by a-koka** [Kudo/react-native-v8#43]
Using `url("$rootDir/../node_modules/v8-android-nointl/dist")` doesn't work on my `react-native` version of `0.61.5`. Using the regular version ie. removing `nointl` works. Are all `nointl` versions being published properly?

**Comment by Kudo** [comment]
nointl package is not depended by default and you should [add by hand](https://github.com/Kudo/react-native-v8#how-to-reduce-apk-size-).
Please check if v8-android-nointl is existed in your node_modules.

**Comment by a-koka** [comment]
I feel so stupid. Thank you!
