### ISSUE TITLE
mention android-v8 flavours

### ISSUE THREAD

**Issue by sirpy** [Kudo/react-native-v8#45]
add to docs how to install different flavour of android-v8 like JIT

**Comment by codecog** [comment]
I will create a PR with instructions to use different flavours over the weekend 👍

**Comment by gpawlik** [comment]
@codecog any update on this?

**Comment by codecog** [comment]
@gpawlik https://github.com/Kudo/react-native-v8/pull/47

**Comment by gpawlik** [comment]
Thanks!

**Comment by Kudo** [comment]
Thanks to @codecog that #47 was merged and I am going to close this.
