### ISSUE TITLE
nointl stopped working

### ISSUE THREAD

**Issue by a-koka** [Kudo/react-native-v8#48]
`nointl` suddenly stopped working for my app, no code changes were made. Removing it works.

Below is my error:
` Could not find any matches for org.chromium:v8-android:+ as no versions of org.chromium:v8-android are available`

This is my version:
`"react-native-v8": ">=0.61.5-patch.0 <0.61.6",`

**Comment by Kudo** [comment]
Please make sure gradle could find the v8-android dependency.
```gradle
allprojects {
    repositories {
        // ...
        maven {
            url("$rootDir/../node_modules/v8-android-nointl/dist")
        }
    }
}
```

BTW, what's the v8-android-nointl version you used?

**Comment by a-koka** [comment]
That is indeed the change that breaks my build.

*gradle.build* like below works:
```
maven {
            // prebuilt libv8android.so
            url("$rootDir/../node_modules/v8-android/dist")
         }
```

My *package.json* has this:

`"v8-android-nointl": "^8.80.1"`

Do I need to update my version?

This just started happening recently and there weren't any major code changes to my project. A `gradlew clean` caused this to start happening.

**Comment by Kudo** [comment]
build.gradle should be like that
```patch
maven {
            // prebuilt libv8android.so
-            url("$rootDir/../node_modules/v8-android/dist")
+            url("$rootDir/../node_modules/v8-android-nointl/dist")
         }
```

**Comment by a-koka** [comment]
Yes, that is indeed the change that breaks my build. As shared earlier, this was all working a few days ago.

```
Could not find any matches for org.chromium:v8-android:+ as no versions of org.chromium:v8-android are available.
```

**Comment by Kudo** [comment]
I am not sure how you working previously.
However, to use nointl version you should:

1. has v8-android-nointl in node_modules. (e.g. by `yarn add v8-android-nointl`)
2. build.gradle should search dependency in v8-android-nointl.
    i.e. the change above is expected.

**Comment by a-koka** [comment]
Please look at my issue above, I've included the line in package.json.

Here it is again for your ease:

```
"react-native-v8": ">=0.61.5-patch.0 <0.61.6",
"v8-android-nointl": "^8.80.1"
```

**Comment by Kudo** [comment]
Please help to check if the v8-android-nointl folder is existed.
```patch
+ println "search v8-android at $rootDir/../node_modules/v8-android-nointl/dist"
allprojects {
    repositories {
        // ...
        maven {
            // prebuilt libv8android.so
            url("$rootDir/../node_modules/v8-android-nointl/dist")
        }
    }
}
```

Execute gradle and get the output like
`search v8-android at /path/to/V862/android/../node_modules/v8-android-nointl/dist`

Then check if the file is existed or not.
`ls /path/to/V862/android/../node_modules/v8-android-nointl/dist/org/chromium/v8-android/8.80.1/v8-android-8.80.1.aar`

**Comment by a-koka** [comment]
Thank you! Not sure how but `$rootDir/../node_modules/v8-android-nointl` was no longer in place. A simple `npm i` fixed the problem.
