### ISSUE TITLE
react native version mismatch

### ISSUE THREAD

**Issue by tamacroft** [Kudo/react-native-v8#50]
I have upgrade react native version to 0.63, but if i run on android, show error "react native version mismatch" 0.63 with 0.62, but if i run in simulator, its work and no error pop up.

**Comment by khalisafkari** [comment]
Same

**Comment by tamacroft** [comment]
temporary I update manual this lib in node_modules

**Comment by Kudo** [comment]
Please try `react-native-v8@0.63.0-patch.0` or `react-native-v8@0.63.1-patch.0` and feel free to let me know if you encounter any problems.
Thank you.

**Comment by Kudo** [comment]
I am going to close this issue. Please feel free to let me know if there are any further problems after upgrading to `0.63.*-patch.*`
