### ISSUE TITLE
New Patch for react-native 0.63

### ISSUE THREAD

**Issue by jinshin1013** [Kudo/react-native-v8#51]
### The problem
Does `react-native-v8` have to release a patch for `react-native@0.63`? Or should the existing `react-native@0.62` patch work fine? 

Related to #50

**Comment by Kudo** [comment]
RN 0.63 support is ready.
Please try `react-native-v8@0.63.0-patch.0` or `react-native-v8@0.63.1-patch.0` and feel free to let me know if you encounter any problems.
Thank you.

**Comment by jinshin1013** [comment]
@Kudo The new patch worked great! Cheers :)

**Comment by Gutyn** [comment]
@Kudo do you have a quick doc on how to build v8? I have a fork of RN and a fork of v8 and I used to do fine:
`rm -rf build && rm -rf dist && scripts/build.sh && tar cvfz dist.tgz dist`
and now it fails with multiple problems.
Are you able to help me real quick? Thank you.
