### ISSUE TITLE
Pros and cons

### ISSUE THREAD

**Issue by muhammadwafa** [Kudo/react-native-v8#53]
`Why should we use v8 engine in react-native?`
 Could someone please help what is the main benefit of **v8 engine over javascript core**.

`When should we use v8 engine in react-native?`
 Which time actually we are in need of **v8 engine**.

`Is there cons points of using v8 engine in react-native?`

**Comment by Kudo** [comment]
IMO, the selling point is v8-android-jit.
If your app relies on heavily JS computing power, V8 with JIT is the best choice.

On the other hand, the disadvantage of V8 is about its binary size.
It will increase final APK size.

**Comment by muhammadwafa** [comment]
@Kudo thank you,

Could you please let me know, is v8 still better than hermes? will v8 compiled and worked on ios too? as you know hermes only available on Android.

**Comment by Kudo** [comment]
> is v8 still better than hermes?

It depends. If you are talking about JS performance, V8 with JIT should be better than Hermes.
On the other hand, Hermes's binary size is dramatically smaller than V8.
This is also a reason Hermes's TTI is fast.
 
> will v8 compiled and worked on ios too?

Supposedly yes, please check [react-native-template-v8](https://github.com/Kudo/react-native-v8/blob/master/packages/react-native-template-v8/README.md)

> as you know hermes only available on Android.

AFAIK, Hermes has macOS support now. In theory, iOS support is also possible.

**Comment by muhammadwafa** [comment]
Thank you very much
