### ISSUE TITLE
Different variant depending on buildType or ENV ?

### ISSUE THREAD

**Issue by OlivierFreyssinet** [Kudo/react-native-v8#55]
Is it possible to configure gradle so that it takes a different v8 variant depending on the app's buildType ?

I would like to use `v8-nointl` in production but `v8-jit-nointl` in debugging to avoid impacting the battery too much in prod but at the same time have the best development experience with blazing fast reloads thanks to JIT compilation.

If it was configured in app/build.gradle then I would do something like this:
```gradle
dependencies {
  // ...
  debugImplementation  project(:'v8-jit-nointl')
  releaseImplementation project(:'v8-nointl')
}
```

The `buildType` is defined in `app/build.gradle` so I guess it's impossible to do it like this in the project's `build.gradle`, but is there a way to get to the same end result ? Maybe by using an environment variable ?

**Comment by Kudo** [comment]
It is possible for gradle to specify exact path.
You could refer from [hermes setup](https://github.com/facebook/react-native/blob/master/template/android/app/build.gradle#L207-L209)

**Comment by Kudo** [comment]
Going to close this issue as there are no further responses. Please feel free to reopen or open new one if there are any other problems.
