### ISSUE TITLE
Confirm v8 installation

### ISSUE THREAD

**Issue by jacquesdev** [Kudo/react-native-v8#56]
We recently started using the INTL in our app, and for some of users it seems it's not supported (getting crash alerts). This surprised us because we assumed that v8 supported, and since I assume it does, I'm guessing it's possibly not installed properly.

Can someone please confirm how I could doublecheck that? I saw there was some mention of it not being support in the debugger, so just wanted to understand what else I could do?

**Comment by Kudo** [comment]
Needs more information for this.
1. Is it correct that "with the same APK, some user run with Intl support and some did NOT."?
2. Could you share the crash backtrace?
3. Assuming you could not reproduce the problem in house, is it true?

Thank you and hopefully we could find some way to find the problems.

**Comment by jacquesdev** [comment]
Hello @Kudo .

I was going through crash logs and noticed that I totally missed the platform, which in this case was not even Android related.🤦‍♂️ (Was iOS9).

But that made the fix so much easier, thank you!

**Comment by jacquesdev** [comment]
And sorry for wasting your time

**Comment by Kudo** [comment]
No problems. Feel free to let me know if there are any further questions.
