### ISSUE TITLE
RN 0.63.3 support

### ISSUE THREAD

**Issue by kmkrtich** [Kudo/react-native-v8#57]
This issue is just for getting info when we will get update for React Native 0.63.3 ?
Because React 0.63.2 is very bad release and is having a lot of issues on IOS.

**Some issues/notes related to 0.63.2-patch.1**
- app startup time was increased from 2.2s to 2.6s (hermes is already 1.5s)
- app size was increased by 4MB (not sure whether it's connected with engine)

**Comment by Kudo** [comment]
0.63.3-patch.0 published, please take a look.

For the app startup time / size, which previous version did you compared from?

**Comment by kmkrtich** [comment]
> 0.63.3-patch.0 published, please take a look.
> 
> For the app startup time / size, which previous version did you compared from?

Wow, cool.
Startup time comparison was done with 0.61.5

**Comment by Kudo** [comment]
The were a lot of changes in react-native between 0.61 and 0.63.
I am afraid that the differences are from react-native internally.

If you would like to compare more in detail, I've publish `react-native-v8@0.61.5-patch.4`.
The v8runtime implementation are exactly the same with 0.63.3-patch.0.
As well as that they all use v8-android 8.84.0.

**Comment by Kudo** [comment]
Going to close this issue as there are no further response. Please feel free to reopen or open new one if there are any other problems.
