### ISSUE TITLE
Question: Future of react-native-v8

### ISSUE THREAD

**Issue by bhaskarGyan** [Kudo/react-native-v8#6]
Hi @Kudo , Since react has officially launch Hermes, what would be future of this package?
Will it co exist with Hermas and user can opt in for react-native-v8 base on use case for future versions of react-native?

I am not able to compare performance of this package with Hermes due to an open issue in react-native https://github.com/facebook/react-native/issues/25601.

Will share the perf result one above issue is resolved

**Comment by Kudo** [comment]
@bhaskarGyan Yes, I will keep maintain react-native-v8. V8 also has some advanced features like Intl or WebAssembly, it should be good for RN user to have another JS runtime option.

And thanks for your work to compare memory info between these runtimes.
Will take a look for the Hermes RN integration issue you mentioned.

**Comment by bhaskarGyan** [comment]
Awesome...

Thanks for all the hard work you have put in into react-native-v8. 

Also, I am now able to use Hermes. Based on initial observation Hermas looks good but not better than v8 in terms of memory allocation(during stress testing).

I will share the results of v8 vs Hermas shortly
