### ISSUE TITLE
RN 0.63.4 support ?

### ISSUE THREAD

**Issue by dcboy** [Kudo/react-native-v8#61]
when support RN 0.63.4 ?
thx

**Comment by vtoupet** [comment]
Up. I am also interested

**Comment by Kudo** [comment]
Sorry for late.
react-native-v8@0.63.4-patch.0 is published. Please take a look.
Thanks.

**Comment by dcboy** [comment]
> Sorry for late.
> 
> react-native-v8@0.63.4-patch.0 is published. Please take a look.
> 
> Thanks.

Thx so great

**Comment by Kudo** [comment]
Going to close this issue. Please feel free to open new one if there are any other problems.
