### ISSUE TITLE
Support v8 of RN 0.64

### ISSUE THREAD

**Issue by exneval** [Kudo/react-native-v8#66]
React Native 0.64 stable just out
It will be great to support that version with v8

cc @Kudo 
Thanks for the hard work

**Comment by rosskhanas** [comment]
@Kudo is it ok to use `react-native-v8@0.64.0-patch.0` with `react-native@0.64.2`? If not, is there a chance to make a patch for `0.64.2`? Thank you 😊

**Comment by Kudo** [comment]
@rosskhanas `react-native-v8@0.64.2-patch.0` is published. please take a look.
if there are any problems and report an issue to me. thanks!
