### ISSUE TITLE
could I use latest version for 0.63.4

### ISSUE THREAD

**Issue by aniltirola** [Kudo/react-native-v8#67]
Hi @Kudo,
thanks for your awesome work; I realized latest patches including until Mar 17, 2021.
Would you also provide a version including these patches for using with react-native `0.63.4`?
We use in  our environment `react-native-v8` with `v8-android-nointl`.

Regards anil

**Comment by Rohan-ult** [comment]
Are you looking for this [ #61](https://github.com/Kudo/react-native-v8/issues/61) ?
Also, there is two patches for `0.63.4`
1. [ react-native-v8@0.63.4-patch.0](https://www.npmjs.com/package/react-native-v8/v/0.63.4-patch.0) Published 3 months ago
2. [ react-native-v8@0.63.4-patch.1](https://www.npmjs.com/package/react-native-v8/v/0.63.4-patch.1) Published a month ago

**Comment by aniltirola** [comment]
thanks @Rohan-ult !
I already use `react-native-v8@0.63.4-patch.1`.
But I was interested in the patches after `Feb 18 2021`, but I don't know if this would make sense.

**Comment by Kudo** [comment]
@aniltirola The patches was only for RN 0.64, basically to fix build break from RN changes.
There are no differences between `0.63.4-patch.1` and `0.64.0-patch.0`.
