### ISSUE TITLE
You can show the android complete build.grade

### ISSUE THREAD

**Issue by xmw1992** [Kudo/react-native-v8#7]
I follow your procedure and can't replace the engine.can you show the complete build.grade? or provide a demo！
look forward to your reply
thank you!

**Comment by xmw1992** [comment]
when  I to run-android  this error : 
07-25 14:13:09.920 7497-7553/com.rnv8demo E/SoLoader: couldn't find DSO to load: libhermes.so
07-25 14:13:09.921 7497-7553/com.rnv8demo E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.rnv8demo, PID: 7497
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:949)
        at java.lang.Thread.run(Thread.java:818)
07-25 14:13:10.026 7497-7552/com.rnv8demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb407c8a0

**Comment by Kudo** [comment]
I guess you enabled Hermes.
Please make sure that `enableHermes` is false in `android/app/build.gradle`.

**Comment by xmw1992** [comment]
thank you for your reply!
but I didn't open it. enableHermes  is false
and I create a new demo ,this react-native version 0.60.4
maybe I can post my build.grade for your 

packagingOptions {
        pickFirst '**/armeabi-v7a/libc++_shared.so'
        pickFirst '**/x86/libc++_shared.so'
        pickFirst '**/arm64-v8a/libc++_shared.so'
        pickFirst '**/x86_64/libc++_shared.so'
        pickFirst '**/x86/libjsc.so'
        pickFirst '**/armeabi-v7a/libjsc.so'
        exclude "**/libjsc.so"
    }

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules

    if (enableHermes) {
      def hermesPath = "../../node_modules/hermesvm/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
      releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        //implementation jscFlavor
        // Add v8-android - prebuilt libv8.so into APK
        implementation 'org.chromium:v8-android:+'
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url("$rootDir/../node_modules/react-native-v8/dist")
        }
        maven {
            // prebuilt libv8.so
            url("$rootDir/../node_modules/v8-android/dist")
        }
    }
}

The above is part of my grade configuration

look forward to your reply
thank you!

**Comment by Kudo** [comment]
Curiously, what's the react-native-v8 version you used?
For RN 0.60.4, you should use `yarn add 'react-native-v8@>=0.60.4-patch.0 <0.60.5'`
I.e. the react-native-v8 version should match with react-native.

**Comment by xmw1992** [comment]
ok
 I use the react-native-v8@0.60.3-patch.0  
I  update react-native-v8 version to try 
thank you! Kudo

**Comment by xmw1992** [comment]
oh!!  Kudo I'm sorry to trouble you again.
I update this version -->"react-native-v8": ">=0.60.4-patch.0 <0.60.5"
and the result is  global._v8runtime is not a function
I'd like to consult you. how to config this 

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    // Add v8-android - prebuilt libv8.so into APK
    implementation 'org.chromium:v8-android:+'
    if (enableHermes) {
      def hermesPath = "../../node_modules/hermesvm/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
      releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

Because react-native uses the JSC engine by default

how to Handle this " implementation jscFlavor" 
v8 engine Not in force

look forward to your reply
thank you!

**Comment by xmw1992** [comment]
hi! Kudo 
 simulator can use v8 engine?

**Comment by Kudo** [comment]
I just initiated a project from pure RN 0.60.4.
Please take a look the patch file to apply V8. https://gist.github.com/Kudo/fa8e5afc688b678c1fe08e7b00433991#file-rn_v8_0_60_4-patch
In case you need step-by-step, there is also an apply.sh
https://gist.github.com/Kudo/fa8e5afc688b678c1fe08e7b00433991#file-apply-sh

> simulator can use v8 engine?

react-native-v8 should work well on Android emulators.

**Comment by xmw1992** [comment]
ok I try!
 thank you  very much!

**Comment by xmw1992** [comment]
wow, it's cool. 
I finally succeeded in running it.
thank you very much for your patient guidance. 
thank you! Kudo
