### ISSUE TITLE
Does this package work well with RAM Bundles?

### ISSUE THREAD

**Issue by omranjamal** [Kudo/react-native-v8#74]
Just curious if this package can efficiently load RAM bundles or does it load it all in one go even if it's a RAM bundle?

**Comment by AbhiGhorai** [comment]
@Kudo could you answer this, its important for us to know about the RAM bundle support.

**Comment by Kudo** [comment]
RAM bundles doesn't rely on some specific js engine features, so it should be supported. please refer this react native document to verify: https://reactnative.dev/docs/ram-bundles-inline-requires#enable-the-ram-format
