### ISSUE TITLE
V8 crash in RN 0.64.2

### ISSUE THREAD

**Issue by PaulDuong1** [Kudo/react-native-v8#78]
I'm trying to upgrade RN to 0.64.2, and I upgrade v8 patch too, but still met some problem.

This is the crash info I got from android studio

`D/SoLoader: About to load: libyoga.so
D/SoLoader: libyoga.so not found on /data/data/com.shipt.groceries_staging/lib-main
    libyoga.so found on /data/app/com.shipt.groceries_staging-fgDcIFJvur8qvf05CqH-wg==/lib/x86
    Not resolving dependencies for libyoga.so
D/SoLoader: Loaded: libyoga.so
D/SoLoader: About to load: libreactnativeblob.so
D/SoLoader: libreactnativeblob.so not found on /data/data/com.shipt.groceries_staging/lib-main
    libreactnativeblob.so found on /data/app/com.shipt.groceries_staging-fgDcIFJvur8qvf05CqH-wg==/lib/x86
    Not resolving dependencies for libreactnativeblob.so
D/SoLoader: Loaded: libreactnativeblob.so
I/flipper: flipper: FlipperClient::addPlugin Fresco
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xffffc100 in tid 18955 (mqt_js), pid 18600 (oceries_staging)`

Anyone have any idea?

**Comment by Kudo** [comment]
please provide more adb log or having a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by PaulDuong1** [comment]
@Kudo Just want to be clear, updating V8 should just update patch version in package.json right?

**Comment by PaulDuong1** [comment]
> @Kudo Just want to be clear, updating V8 should just update patch version in package.json right?

I think I find what's going wrong, we are using V8 variant v8-android-jit-nointl and I forgot to update it at the same time.

But that wired error can not remind me that I forgot to do something, I still don't where that error came from.
