### ISSUE TITLE
App crash on RN 0.65.1

### ISSUE THREAD

**Issue by makarkotlov** [Kudo/react-native-v8#83]
Hi! Thank you for your awesome work! I need your help to figure out why RN app crashes on startup, because I don't have much experience debugging native crashes.

I used:
"react-native": "0.65.1",
"react-native-v8": "^0.65.1-patch.0",
"v8-android-nointl": "^9.93.0"

And I got this error:

`A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x605 in tid 4818 (mqt_js), pid 4779`

But everything works fine if I use jit version, I don't know why. You can definitely reproduce it on clean RN project

**Comment by Kudo** [comment]
i test on clean RN 0.65.1 project and works fine for me.
can you try to remove node_modules and reinstall packages again?
besides, please double confirm the maven repo like this (must be `v8-android-nointl`)

```
        maven {
            // prebuilt libv8android.so
            url("$rootDir/../node_modules/v8-android-nointl/dist")
         }
```

**Comment by makarkotlov** [comment]
oh that's weird, can you check this repo please https://github.com/makarkotlov/react-native-snake-game/tree/v8? I did everything you advised and config seems alright but the error persists. Thank you in advance

**Comment by Kudo** [comment]
i just cloned your repo and it works fine for me. maybe just one difference: i deleted `package-lock.json` and used `yarn install` instead.

**Comment by makarkotlov** [comment]
Thank you very much! My issue has something to do with android emulator. It works on real device, so I'm closing the issue. Thanks again!
