### ISSUE TITLE
Whether to support versions prior to RN 0.6？

### ISSUE THREAD

**Issue by songxiaoliang** [Kudo/react-native-v8#9]
Whether to support versions prior to RN 0.6

**Comment by Kudo** [comment]
I have added a version to support RN 0.59.10.
`yarn add 'react-native-v8@>=0.59.10-patch.0 <0.59.11'`
The other setup instructions are pretty much same as in [README](https://github.com/Kudo/react-native-v8/blob/master/README.md#integration-with-react-native).

For version prior RN 0.59.10,  I am not considering to backport in the mean time.
Hopefully this 0.59.10 version did help for you.

**Comment by Kudo** [comment]
I am getting to close this issus. Feel free to let me know if you have any other questions.

**Comment by songxiaoliang** [comment]
@Kudo Hi Kudo, I am very happy to receive such a wonderful reply. Currently my project is based on React Native: 0.57.7. In particular, I want to improve the current js engine on the Android side to improve the performance of the experience. So, is there a consideration for compatibility with 0.57? Or do you have any better solutions for me? Thanks again

**Comment by Kudo** [comment]
I am sorry that RN 0.57 still use old way to integrate JS engine. i.e. the [JSExecutor](https://github.com/facebook/react-native/blob/0.57-stable/ReactCommon/cxxreact/JSExecutor.h).
My work is based on RN JSI which is incompatible with JSExecutor.
I don't have plan to backport JSExecutor, sorry for that.

**Comment by songxiaoliang** [comment]
@Kudo Thanks, getting better and better

**Comment by Kudo** [comment]
@mars-lan Yes, please make sure the version is aligned to RN.
I.e. RN 0.59.10 should use RNV8 0.59.10-patch.N.
