### ISSUE TITLE
0.59.10-patch.6    v8-android: 8.80.0 ?

### ISSUE THREAD

**Issue by wangchongwei** [Kudo/react-native-v8#94]
my project react-native version: 0.59.10
Look at README 
org.chromium:v8-android  should be 7.8.+
but  at 
node_modules/react-native-v8/package.json
```
"dependencies": {
    "v8-android": "~8.80.0"
  },
```

Is it right?

**Comment by Kudo** [comment]
fixed via https://github.com/Kudo/react-native-v8/commit/8163f99da377f478693be28d7ccfe2dbef046c76. thanks for your finding!
