### ISSUE TITLE
Will react-native-v8 support the new RN architecture?

### ISSUE THREAD

**Issue by jzxchiang1** [Kudo/react-native-v8#96]
Like Fabric and TurboModules? I'm not sure if it needs any custom integration with a JS engine...

It [seems](https://reactnative.dev/blog/2022/03/15/an-update-on-the-new-architecture-rollout) like this year will be the year that the new architecture finally rolls out.

**Comment by Kudo** [comment]
i think the answer is yes. the new architecture is based on JSI. there's no JSI difference between the old architecture and the new architecture.

**Comment by jzxchiang1** [comment]
Thanks. I would've thought that JSI would require some updates in the JavaScript engine for JavaScript objects to hold pointers to C++ structs... Maybe I'm misunderstanding... 🤔
